### ISSUE TITLE
eth_estimateGas now accept extra parameter

### ISSUE THREAD

**Issue by yarkinwho** [eosnetworkfoundation/eos-evm-node#106]
It now accept a second parameter to specify block and some clients are starting to send such txs

We can either choose to support this or remove the sanity check to make the rpc ignore this extra input (as in most of times you will only call estimate gas with latest..)

**Comment by arhag** [comment]
For now (for this issue), we will have partial support of the second parameter (described in https://ethereum.github.io/execution-apis/api-documentation/).

We will return a `-39001: Unknown block` error if the block tag is `earliest`, `finalized`, or `safe`. If the tag is `latest` or `pending` then we will execute the transaction to estimate gas on the latest block. This means `pending` is acting like `latest` (effectively as if there is nothing in the mempool).
