### ISSUE TITLE
Always ensure block is added to database regardless of header existing in cache

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/eos-evm-node#153]
Related to #148 and #147

**Comment by elmato** [comment]
Investigate a better solution for the one line fix [here](https://github.com/eosnetworkfoundation/silkworm/tree/elmato/hack-execution-engine-insert-block)

**Comment by elmato** [comment]
silkworm issue https://github.com/eosnetworkfoundation/silkworm/issues/112
