### ISSUE TITLE
Return saved gas price parameter in eth_gasPrice call

### ISSUE THREAD

**Issue by yarkinwho** [eosnetworkfoundation/eos-evm-node#188]
Depends on #186

Currently the eth_gasPrice call from node is not used in our system and will return wrong number.

We could change it to return minimum gas fee saved in #186 

This will make it easier to debug related issues and pave the way for letting node reply to this call (may need extra works after we adopt SHANGHAI fork) in the future.

**Comment by stephenpdeos** [comment]
We will hold off on this until London Hard Fork design has been completed
