### ISSUE TITLE
Some MDBX flag maybe wrong

### ISSUE THREAD

**Issue by yarkinwho** [eosnetworkfoundation/eos-evm-node#189]
https://github.com/eosnetworkfoundation/eos-evm-node/blob/6b983015a44c0ff47eead0083d2b3637b5a08030/src/engine_plugin.cpp#L67C9-L81C11

We may use the exclusive and shared flag in a wrong way.

Those flags are there if the file will be accessed by different processes, which is not our case.

And by setting the exclusive flag, according to docs, there will be extra limitation:

OS kernel (i.e. file system and memory mapping implementation) and all processes that open the given environment MUST be running in the physically single RAM with cache-coherency. The only exception for cache-consistency requirement is Linux on MIPS architecture, but this case has not been tested for a long time).

I suspect this may be the cause for those MDBX_MAP_FULL we encountered.

**Comment by yarkinwho** [comment]
Verified that changing those two flags: exclusive = true, shared = false can indeed make the node go beyond the point that was reporting MDBX_MAP_FULL.

Need more research whether this change is safe or whether this is the root cause or just a workaround.

**Comment by yarkinwho** [comment]
Suggestion:

1 Re create the scene
2 use mdbx_stat -e to confirm if it's indeed the mapsize issue
3 try exclusive and shared flag separately. Currently shared flag is more suspicious as it will set the MDBX_ACCEDE which will cause the program to use the settings stored in the db. This might caused the issue.

**Comment by stephenpdeos** [comment]
Document and review findings for cause as well

**Comment by yarkinwho** [comment]
The difference come from here:
In https://github.com/eosnetworkfoundation/silkworm/blob/d3e6ead809e9a5049d169d5eb8dfb0fa86d98db2/silkworm/node/db/mdbx.cpp#L134-L141

When node open the db, the parameters are passed in only when opened WITHOUT shared flag.
It seems that we assume when we open the db in shared mode, it suppose to use the existing parameters. 
Yet, this is not the case, the client will overwrite those db size related parameter regardless the shared flag.

Node currently is passing shared flag all the time except the first time. So the size limits are properly set in the beginning then reset to default value (which is memory * 207 / 128 so around 26G for 16G machine) when node reboot. 

What makes thing worse is, it seems that some bug in rpc implementation caused the rpc process open the db in read-write mode as well and reset the mapsize configs as well...

Suggested way to fix:

1 make node not using shared mode, node are not suppose to open the db when someone else is writing to it anyway. So it's fine the fail the open in such cases. (shared flag will only affect the process of opening the db, not the state of the opened db)
2 fix the rpc to properly set readonly flag... and make sure it will indeed work with the flag.
3 it seems exclusive flag has nothing to do with this issue, we let's just leave it alone.

**Comment by yarkinwho** [comment]
Fixing of the issue will be tracked by #203 #204
