### ISSUE TITLE
segfault when ship is not reachable

### ISSUE THREAD

**Issue by cc32d9** [eosnetworkfoundation/eos-evm-node#25]
I upgraded the node from an existing database, and when I started it, the ship was not available. The node coredumped.

**Comment by yarkinwho** [comment]
We have --ship-max-retry to control how many times we will retry connecting to ship. It's defaulted to 0 which means the system will give up and exit directly. Therefore, exit on a unreachable ship is working as intended. 

But yes we should make sure the exit process is more graceful and try not triggering segfaults (current way to exit seems will eventually lead to segfault). tracked by #29
