### ISSUE TITLE
failed to recover "from" address from special signatures

### ISSUE THREAD

**Issue by taokayan** [eosnetworkfoundation/eos-evm-node#26]
failed to recover 2 types of special signatures:

Type 1: r == 0, s < UINT64_MAX:, then expected "from" should be 0xbb bb bb bb bb bb bb bb bb bb bb bb  (uint64_t)s 
Type 2: r == 0, s  starts with 0xff ff ff ff ff ff ff ff ff ff ff ff, then expected "from addr" is the following 20 bytes of s.
otherwise, use the standard secpk1 algorithm to recover "from addr" from s, r & y_parity.

**Comment by yarkinwho** [comment]
Fix should be in silkworm. Please bring in missing submodule updates as well.
