### ISSUE TITLE
Gas parameter fork handling test instability

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/eos-evm-node#282]
Integration test instability

https://github.com/eosnetworkfoundation/eos-evm-node/actions/runs/10458468600/job/28961275786

**Comment by arhag** [comment]
The problem was discovered to be a bug in Spring (https://github.com/AntelopeIO/spring/issues/815) and once the Spring bug is fixed, this issue should also be resolved.

**Comment by arhag** [comment]
Resolved by the Spring bug fix https://github.com/AntelopeIO/spring/pull/816.
