### ISSUE TITLE
evmnode will not recover from blocks applied but then forked while not running

### ISSUE THREAD

**Issue by spoonincode** [eosnetworkfoundation/eos-evm-node#39]
If evmnode is shut down with a head block that is forked out while it is shut down, upon start up it will not properly follow the new fork. For example, if evmnode has applied blocks `1->2->3->4->5` from ship, evmnode is shutdown, block 4 & 5 is forked out, leading to a new chain `1->2->3->4*->5*->6->7`, evmnode will incorrectly start at block 6 on restart when it really needs to start at block 4*

Typically there are two ways to protect against this:
* Use ship's `have_positions` in the block request. This is ship's intended mechanism to protect against this scenario and typically involves the least complexity on the client side.
* Always start ship streaming at LIB, and then manually look for forks up to head block. This doesn't require usage of `have_positions`, but it puts more onus on the client  to figure out what has or hasn't been forked out if that matters to it.

It's possible that evmnode can simply _always_ start at LIB and simply _always_ apply all blocks from LIB. It would re-apply existing blocks but this may not disturb it.

**Comment by stephenpdeos** [comment]
We are now starting from the last irreversible block so this should no longer be a problem
