### ISSUE TITLE
Trace Executor does not generate trace for transfer/call to pre-compile addresses

### ISSUE THREAD

**Issue by yarkinwho** [eosnetworkfoundation/eos-evm-node#48]
A transfer to 0x0000.....001 will trigger the issue

curl localhost:8881 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"trace_replayBlockTransactions","params":["818076",["trace"]],"id":1,"jsonrpc":"2.0"}'

**Comment by arhag** [comment]
I assigned the EVM Node 0.6.0-rc2 milestone to this issue to indicate that the code changes should go into the `release/0.6` branch. But I do not consider this a block to getting a v0.6.0-rc2 out or even getting v0.6.0 stbale out.
