### ISSUE TITLE
eos-evm-rpc: eth_getLogs fails with error "failed alloc while reading"

### ISSUE THREAD

**Issue by elmato** [eosnetworkfoundation/eos-evm-node#51]
Depends on https://github.com/eosnetworkfoundation/silkworm/issues/60.

**Comment by arhag** [comment]
Reopening because https://github.com/eosnetworkfoundation/eos-evm-node/pull/54 brought in the wrong commit for the silkworm submodule. It should be the merge commit d7e96f9 of https://github.com/eosnetworkfoundation/silkworm/pull/66.
