### ISSUE TITLE
Apply rate_limit to tx_proxy

### ISSUE THREAD

**Issue by yarkinwho** [eosnetworkfoundation/eos-evm-node#85]
It seems some poorly written dApps might generate request storm upon failed requests. 

rate_limit might help containing this issue.

Some rate limiting before AWS LB might be enough, but it would be nice if we have another layer of protection in tx_proxy.

Be careful to apply rate_limit according to real ip as we are behind a lb.

**Comment by stephenpdeos** [comment]
Should place a rate limit on the nginx proxy of 10 requests per seconds per IP

**Comment by yarkinwho** [comment]
After some test on testnet machine. The limit is set to 5r/s with burst 25

But the limit is on dry run mode. 

We should review the logs after we upgrade to 0.7.0 and figure out the proper limit then turn on the limit.

We can either use another issue to track the process or continue using this issue.
