### ISSUE TITLE
Formalize the quirk mode for blockscout trace calls

### ISSUE THREAD

**Issue by yarkinwho** [eosnetworkfoundation/eos-evm-node#88]
We observed blockscout will mark failed txs as "succeed" when working with 0.6 eos-evm-node.

The root cause of the issue is that in 0.6, the traces will have both error and result field set but blockscout does not anticipate that. 

Discussion in https://github.com/blockscout/blockscout/issues/8623 shows blockscout will keep this behavior until we have stronger arguments supporting the new behavior.

Therefore, we need a quirk mode for this in our end.

Currently the binary on evm4explorer machines are patched to behave as anticipated by blockscout. We need to make this change formal.

**Comment by yarkinwho** [comment]
The quirk flag seems working properly but the fix for trace itself has some problem. 

Reopen this issue for now.

**Comment by arhag** [comment]
This was completed as part of 0.6.3 but there was a problem with the fix that needs to be addressed. That problem is now tracked as part of https://github.com/eosnetworkfoundation/eos-evm-node/issues/120.
