### ISSUE TITLE
Fix CICD Authentication

### ISSUE THREAD

**Issue by kj4ezj** [eosnetworkfoundation/eos-evm-node#9]
From the customer (@arhag):

> Hey @kj4ezj. We migrated eos-evm-node and eos-evm-rpc from the eos-evm repo to the eos-evm-node repo. 
>
> The CI in the eos-evm-node repo is failing (https://github.com/eosnetworkfoundation/eos-evm-node/actions/runs/5582930543/jobs/10202724178). I suspect it has to do with the fact that the secrets weren't copied over to the new repo.
>
> Would you be able to quickly confirm if that is the case and copy them over to the new repo?

> https://github.com/eosnetworkfoundation/eos-evm-node/settings/secrets/actions
>
> Repository secrets: `TRUSTEVM_CI_APP_ID` and `TRUSTEVM_CI_APP_KEY` are missing.

**Comment by kj4ezj** [comment]
I believe the CICD authentication using GitHub app integration should be removed, instead of updated, because this repo and all submodules are now public.

**Comment by arhag** [comment]
This issue has been resolved.

See: https://github.com/eosnetworkfoundation/eos-evm-node/actions/runs/5624565915/job/15412864052#step:2:2

The problem preventing that job from succeeding are irrelevant to the issue captured in this ticket, and is instead being tracked in a new ticket: https://github.com/eosnetworkfoundation/eos-evm-node/issues/15
