### ISSUE TITLE
Ensure EVM block header nonce captures EOS EVM version

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/eos-evm-node#98]
Depends on https://github.com/eosnetworkfoundation/eos-evm-node/issues/97

Additional context: https://hackmd.io/VCpJ5OMwRCigqrD3Kcl_ag

For an EVM block created in response to a new EVM transaction to process, the nonce field should be set to the EOS EVM version capture within the `evmtx` action for that EVM transaction. If supporting the legacy mode of a `pushtx` action that does not emit an `evmtx` action then the nonce should be 0.

If processing a new EVM transaction when the EVM block to include it within already exists then EOS EVM node should assert the nonce of that EVM block header matches the EOS EVM version captured with the `evmtx` action for that EVM transaction. 

If creating an empty EVM block to fill up the time based on the EOS EVM block mapping rules, then the nonce of that new empty block should be the same as the nonce of the previous block.

**Comment by arhag** [comment]
Closing since this task was subsumed by https://github.com/eosnetworkfoundation/eos-evm-node/issues/97.
